name: workshop-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip:
    - azureml-defaults>=1.33.0
    - scikit-learn==0.24.1
    - pandas==1.2.1
    - joblib==1.0.0
    # Only required if you use Application Insights and data collection
    - inference-schema==1.3.0
    - azureml-monitoring
