# Disabled for the sake of this workshop
trigger:
- none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  resourcegroup: 'aml-mlops-workshop' # replace with your resource group (same as you've used for the Service Connection)
  workspace: 'aml-mlops-workshop' # replace with your workspace name (same as you've used for the Service Connection)
  model-name: 'credit-model'

  # Azure Resource Manager connection created during pipeline creation
  aml_service_connection: 'aml_workspace'

steps:
- task: AzureCLI@2
  displayName: 'Install the az ml CLI'
  inputs:
    azureSubscription: '$(aml_service_connection)'
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az extension add -n azure-cli-ml

- task: AzureCLI@2
  displayName: 'Attach folder to AML workspace (authenticate)'
  inputs:
    azureSubscription: '$(aml_service_connection)'
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml folder attach -w $(workspace) -g $(resourcegroup)

- task: AzureCLI@2
  displayName: 'Deploy model to ACI'
  inputs:
    azureSubscription: '$(aml_service_connection)'
    scriptLocation: inlineScript
    scriptType: bash
    workingDirectory: deployment-using-cli/
    inlineScript: |
      LATEST_VERSION=`az ml model list -n $(model-name) --query '[0].version'`
      az ml model deploy -n credit-model-aci -m $(model-name):$LATEST_VERSION \
        --inference-config-file config/inference-config.yml \
        --deploy-config-file config/deployment-config-aci-qa.yml \
        --overwrite
